name: builds

on:
  pull_request: # Run on all pull requests
  push: # Run only on pushes to master
    branches:
      - master
  schedule: # Run monthly
    - cron: "0 0 1 * *"

jobs:
  build:
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            env: SDLVERSION2
            label: Linux (SDL2)
          - os: ubuntu-latest
            env: mingw32
            label: Windows win32 (mingw)
          - os: ubuntu-latest
            env: mingw64
            label: Windows win64 (mingw)
          - os: macos-latest
            env: SDLVERSION2
            label: macOS arm64 (SDL2)
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies Mac
        if: ${{ runner.os == 'MacOS' }}
        run: |
          brew update
          brew install sdl2 sdl2_image
      - name: Install dependencies Linux
        if: ${{ runner.os == 'Linux' }}
        env:
          envvar: ${{ matrix.env }}
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix zip
          if [[ $envvar == "SDLVERSION2" ]]; then
            sudo apt-get install -y libsdl2-image-dev libsdl2-dev
          elif [[ $envvar == "mingw32" ]]; then
            sudo apt-get install -y gcc-mingw-w64-i686 g++-mingw-w64-i686
          elif [[ $envvar == "mingw64" ]]; then
            sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
          fi
      - name: Configure
        env:
          envvar: ${{ matrix.env }}
        run: |
          if [[ $envvar == "mingw32" ]]; then
            export CC="i686-w64-mingw32-gcc"
            ./configure --prefix-dir=${HOME} --os=MINGW --without-asound --without-oss --without-munt --without-sdl --without-sdl2 --without-pulse
          elif [[ $envvar == "mingw64" ]]; then
            export CC="x86_64-w64-mingw32-gcc"
            ./configure --prefix-dir=${HOME} --os=MINGW --without-asound --without-oss --without-munt --without-sdl --without-sdl2 --without-pulse
          else
            ./configure --prefix-dir=${HOME}
          fi
      - name: Build
        run:
          make -j3
      - name: Bundle
        run:
          make bundle_zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenDune ${{ matrix.label }}
          path: bundles/opendune-custom-*.zip
